import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Nav from "@/components/Nav"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "May's next playground",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-dvh bg-amber-700`}
      >
        <header className="bg-red-300 p-4 flex justify-between ">
          <h1 className="text-3xl font-bold self-center"> Playground</h1>
          <Nav />
        </header>
        <main className="flex-1 p-4"> {children}</main>
        <footer className="bg-red-300 p-4">
          <div>© {new Date().getFullYear()} May</div>
        </footer>
      </body>
    </html>
  )
}
